server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  url: http://localhost:8080
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:33070/postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
jwt:
  secret: secret
  expiration: 36_000_000
  tokenPrefix: "Bearer "
  headerString: "Authorization"
logging:
  level:
    web: ${LOG_LEVEL:DEBUG}
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: pro
  url: http://localhost:8080
  datasource:
    username: postgres
    url: jdbc:postgresql://db:5432/postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
jwt:
  secret: secret
  expiration: 36_000_000
  tokenPrefix: "Bearer "
  headerString: "Authorization"
logging:
  level:
    web: ${LOG_LEVEL:WARN}